# Generated by Django 4.2.7 on 2024-03-04 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Студент", "verbose_name_plural": "Студенты"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
            },
        ),
    ]
