# Generated by Django 4.2.7 on 2023-12-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('fullname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('institutes', models.ManyToManyField(to='directions.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directions.institute')),
            ],
        ),
    ]
