# Generated by Django 4.2.7 on 2024-03-04 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("directions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Кафедра", "verbose_name_plural": "Кафедры"},
        ),
        migrations.AlterModelOptions(
            name="direction",
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.AlterModelOptions(
            name="institute",
            options={"verbose_name": "Институт", "verbose_name_plural": "Институты"},
        ),
    ]
