# Generated by Django 4.2.7 on 2024-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forgejo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgejoprofile",
            name="forgejo_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="id in forgejo"
            ),
        ),
    ]
