# Generated by Django 4.2.7 on 2024-03-29 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forgejo", "0002_alter_forgejoprofile_forgejo_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forgejoprofile",
            name="forgejo_id",
        ),
    ]
