# Generated by Django 4.2.7 on 2024-04-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgejo', '0003_remove_forgejoprofile_forgejo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgejoprofile',
            name='sha',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='sha'),
        ),
    ]
